# Generated by Django 3.1.3 on 2020-11-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201116_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_liked',
        ),
    ]
