# Generated by Django 3.1.3 on 2020-11-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_userprofile_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_posts',
        ),
    ]
