# Generated by Django 3.1.3 on 2020-11-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_userprofile_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_image'),
        ),
    ]
