# Generated by Django 3.1.3 on 2020-11-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201118_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rate',
        ),
    ]
